[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "paperless-asn-qr-codes"
description = 'Code for generating paperless ASN labels with QR codes'
readme = "README.md"
requires-python = ">=3.7"
license = "GPL-3.0"
keywords = []
authors = [
  { name = "Jan Christian Gr√ºnhage", email = "jan.christian@gruenhage.xyz" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "argparse",
  "reportlab",
  "reportlab_qrcode"
]
dynamic = ["version"]

[project.urls]
Documentation = "https://git.jcg.re/jcgruenhage/paperless-asn-qr-codes#readme"
Issues = "https://git.jcg.re/jcgruenhage/paperless-asn-qr-codes/issues"
Source = "https://git.jcg.re/jcgruenhage/paperless-asn-qr-codes"

[project.scripts]
paperless-asn-qr-codes = "paperless_asn_qr_codes.main:main"

[tool.hatch.version]
source = "vcs"
